/**
 * The terms of service, from "2025-529 DRAFT GLKB Web Access ToS v3.docx".
 *
 * Extracted from the document rather than retyped, for the same reason the
 * privacy notice is: a paraphrase of an agreement is a different agreement.
 *
 * The document marks its sections with bold text rather than heading styles,
 * so they are detected by that. Blocks: h = section heading, p = paragraph,
 * li = bullet.
 */
export const TERMS_TITLE = 'Terms of Service (Free/Paid)';
export const TERMS_SUBTITLE = 'University of Michigan Innovation Partnerships File: 2025-529';
export const LAST_UPDATED = 'Date last updated: August 14, 2026';

export const TERMS = [
    ['p', 'The Regents of the University of Michigan (“MICHIGAN”) are making the Materials (as defined below) available to you (“You” or “Your”) through the Genomic Literature Knowledge Base Web Access (GLKB Web Access) website located at < https://glkb.org/ > (“PROGRAM”). GLKB is an AI-powered research engine that synthesizes biomedical literature into structured, evidence-backed answers grounded in real publications, not just predictions. Please read these terms of service carefully before using PROGRAM or the PROGRAM Materials. These terms of service govern Your access to and use of PROGRAM and the PROGRAM Materials and create a binding agreement ( “Agreement”) between You and MICHIGAN. IF YOU DON’T UNDERSTAND HOW THIS AGREEMENT APPLIES TO YOUR ACCESS TO OR USE OF THE PROGRAM MATERIALS, OR YOU THINK THAT YOUR ACCESS TO OR USE OF THE PROGRAM MATERIALS WOULD BE IN VIOLATION OF THIS AGREEMENT, YOU SHOULD CONTACT PROGRAM (see section 10) BEFORE YOU ACCESS OR USE THE PROGRAM MATERIALS. YOU MUST BE AUTHORIZED TO ACCEPT THESE TERMS AND CONDITIONS AS AN INDIVIDUAL. IF YOU DON’T OR CAN’T ACCEPT THESE TERMS AND CONDITIONS PLEASE STOP HERE AND DO NOT ACCESS OR USE PROGRAM OR THE PROGRAM MATERIALS. PROGRAM IS NOT INTENTED FOR USE BY ANYONE UNDER THE AGE OF 13. IF YOU ARE UNDER 13, YOU ARE NOT PERMITTED TO USE PROGRAM.'],
    ['h', '1. PROGRAM Materials'],
    ['p', 'As used in this Agreement, “PROGRAM Materials” means the data, videos, images, text, calculators, and related materials provided through or in connection with PROGRAM. Except for the access and use rights granted in this Agreement, or as otherwise indicated to You separately in writing by MICHIGAN, You have no right, title, or interest in or to PROGRAM or the PROGRAM Materials.'],
    ['h', '2. Access'],
    ['p', 'Regardless of the physical location from which You access or use PROGRAM and the PROGRAM Materials, You will be considered to be accessing or using information technology of the University of MICHIGAN.'],
    ['h', '3. Code of Conduct'],
    ['p', 'You are responsible for all data and content that You access from PROGRAM or create using the PROGRAM Materials (collectively, “Data”). In addition to any other terms and conditions of this Agreement, YOU AGREE TO ABIDE BY THE FOLLOWING RULES:'],
    ['li', 'You will not share passwords or other access information or devices or otherwise authorize any third party to access or use PROGRAM or the PROGRAM Materials on Your behalf.'],
    ['li', 'You will not engage in unlawful, illegal, or fraudulent activity, including, without limitation, by engaging in unauthorized access or unauthorized use of PROGRAM or the PROGRAM Materials or any accounts, computers, or networks related to PROGRAM.'],
    ['li', 'You will not use PROGRAM to make available any unsolicited or unauthorized advertising or promotional materials.'],
    ['li', 'You will not reverse engineer any portion of PROGRAM or the PROGRAM Materials.'],
    ['li', 'Unless indicated to You separately in writing by MICHIGAN, You will not use any robot, spider, site search/retrieval application, or other manual or automated process to access, retrieve, scrape, or index any portion of PROGRAM or the PROGRAM Materials.'],
    ['li', 'You will not record, process, or mine information about other users or creators of the PROGRAM or the PROGRAM Materials.'],
    ['li', 'You will not damage, disrupt, interfere with, diminish, or render inaccessible or unusable PROGRAM or the PROGRAM Materials, PROGRAM or others’ equipment or software or others’ data, or attempt to do so, or encourage or assist others to do so.'],
    ['li', 'You will not initiate a denial of service attack against PROGRAM or the PROGRAM Materials or release a virus, trojan horse, worms or other malware or spyware.'],
    ['li', 'You will not use the PROGRAM Materials to perpetrate a hoax or engage in phishing schemes or forgery or other similar falsification or manipulation of data.'],
    ['li', 'You will not use the PROGRAM Materials to abuse, harass, stalk, threaten, or otherwise violate the legal rights of others.'],
    ['li', 'You will not use the PROGRAM Materials to libel or defame others.'],
    ['li', 'You will not use PROGRAM to make available any content that is vulgar or obscene.'],
    ['li', 'You will not resell or charge others for the PROGRAM Materials, either directly or indirectly.'],
    ['li', 'You will abide by reasonable administrative directives issued from time to time concerning the access or use of PROGRAM or the PROGRAM Materials.'],
    ['h', '4. Suspension and Termination of Your Use of PROGRAM'],
    ['p', 'If You breach or violate the terms and conditions of this Agreement, Your access to PROGRAM and use of the PROGRAM Materials may be suspended or terminated without prior notice to You. You acknowledge that if Your access to and/or use of PROGRAM and the PROGRAM Materials is suspended or terminated, it is possible that You may no longer have access to the content that You created.'],
    ['p', 'You agree that if You breach this Agreement, MICHIGAN may take any available legal actions.'],
    ['h', '5. Changes to Agreement'],
    ['p', 'MICHIGAN reserves the right to update and revise this Agreement at any time. MICHIGAN will change the “Effective Date” at the top of this page so You can determine if the terms of this Agreement have changed since Your last visit. You should routinely check the web page to find out if any changes have been made that affect Your use of the PROGRAM or PROGRAM Materials. Unless otherwise specified, changes made to this Agreement will be effective when they are posted to the web page. IF YOU DO NOT AGREE WITH ANY CHANGES THAT HAVE BEEN MADE, YOU MUST TERMINATE YOUR USE OF PROGRAM AND THE PROGRAM MATERIALS.'],
    ['h', '6. Monitoring'],
    ['p', 'MICHIGAN may monitor Your use of PROGRAM and the PROGRAM Materials to assess compliance with the terms of this Agreement.'],
    ['h', '7. Disclaimer of Warranty and Limitation of Liability'],
    ['p', 'A. THE PROGRAM AND PROGRAM MATERIALS ARE PROVIDED STRICTLY “AS IS” WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. MICHIGAN DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED IN THE PROGRAM WILL MEET YOUR REQUIREMENTS OR THAT OPERATION WILL BE UNINTERRUPTED OR ERROR FREE. THE PROGRAM AND PROGRAM MATERIALS DO NOT PROVIDE CLINICAL AND MEDICAL ADVICE. MICHIGAN shall not be liable for special, indirect, incidental, or consequential damages with respect to any claim on account of or arising from this Agreement or use of the PROGRAM or PROGRAM Materials, even if MICHIGAN has been or is hereafter advised of the possibility of such damages. Because some states do not allow certain exclusions or limitations on implied warranties or of liability for consequential or incidental damages, the above exclusions may not apply to You. In no event, however, will MICHIGAN be liable to You, under any theory of recovery.'],
    ['p', 'B. You agree that MICHIGAN has no obligation to provide to You any maintenance, support, or update services. Should MICHIGAN provide any revised versions of the PROGRAM or PROGRAM Materials to You, You agree that this Agreement shall apply to all such revised versions.'],
    ['p', 'C. IF YOU ARE DISSATISFIED WITH PROGRAM AND/OR THE PROGRAM MATERIALS FOR ANY REASON, OR WITH ANY OF THE TERMS AND CONDITIONS OF THIS AGREEMENT, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE ACCESSING AND USING PROGRAM AND THE PROGRAM MATERIALS.'],
    ['h', '8. Service Availability, SLA, and Support Disclaimer'],
    ['p', 'A. No Uptime Guarantee: The PROGRAM and API access are provided on an "as-available" basis. MICHIGAN does not guarantee uninterrupted, secure, or error-free access to the PROGRAM, and there is no Service Level Agreement (SLA) or uptime commitment associated with this Agreement. Access to the PROGRAM may be temporarily suspended or restricted without notice for administrative reasons, system maintenance, upgrades, network or server failures, or other unforeseen technical issues.'],
    ['p', 'B. Limitation of Liability for Downtime: Under no circumstances shall MICHIGAN, its regents, officers, employees, or developers be liable for any direct, indirect, incidental, or consequential damages, including but not limited to loss of data, research delays, or lost profits, arising out of Your inability to access or use the PROGRAM or APIs at any given time.'],
    ['p', 'C. Best-Effort Support: Technical support, if any, is provided on a "best-effort" basis during standard University of Michigan business hours. MICHIGAN is under no obligation to provide immediate bug fixes, emergency patches, or 24/7 technical assistance.'],
    ['h', '9. Governing Law'],
    ['p', 'This Agreement will be governed by and construed in accordance with the laws of the State of MICHIGAN.'],
    ['h', '10. General'],
    ['p', 'Your access to and use of PROGRAM and PROGRAM Materials are governed by this Agreement and any other terms agreed to in writing. In the event You have any questions about this Agreement, You should contact admin@glkb.org.'],
    ['p', 'If any part of this Agreement is determined to be invalid or unenforceable then the invalid or unenforceable provision will be deemed superseded by a valid enforceable provision that most closely matches the intent of the original provision, and the remainder of this Agreement will continue in effect. The failure of MICHIGAN to exercise or enforce any right or provision of this Agreement will not constitute a waiver of such right or provision. You are prohibited from assigning this Agreement or transferring Your rights under this Agreement to anyone else.'],
    ['h', '11. Third-party content'],
    ['p', 'Through the PROGRAM, You will have the ability to access and/or use content created by other users and/or other third parties, including links to websites and services maintained by third parties. MICHIGAN cannot guarantee that such third-party content, in the PROGRAM or elsewhere, will be free of material You may find objectionable or otherwise inappropriate or free of malware or other contaminants that may harm Your computer, mobile device, or any files therein. Privacy policies and practices for such linked websites may differ from our Privacy Policy [insert link to Privacy Policy]. MICHIGAN disclaims any responsibility or liability related to Your access or use of, or inability to access or use, such third-party content.'],
    ['h', '12. Content You Provide to the PROGRAM'],
    ['h', 'GLKB Web Access Free Tier'],
    ['p', 'The PROGRAM enables you to share Your content such as research questions, prompts, uploaded documents, feedback, and the like (“Content”), with the PROGRAM and its users. You retain all intellectual property rights in, and are responsible for, the Content You create and share.'],
    ['p', 'To the extent that you provide Content, you grant the PROGRAM and MICHIGAN a fully-transferable, royalty-free, perpetual, sublicensable, non-exclusive, worldwide license to copy, distribute, modify, create derivative works based on, publicly perform, publicly display, and otherwise use the Content, including to train machine learning models. This license includes granting the PROGRAM and MICHIGAN the right to use Content with their registered students, on-campus learners, or other learners independent of the PROGRAM. Nothing in this Agreement shall restrict other legal rights the PROGRAM may have to Content, for example under other licenses. We reserve the right to remove or modify Content for any reason, including Content that we believe violates this Agreement or other policies including our Privacy Policy [insert link to Privacy Policy].'],
    ['h', 'GLKB Web Access Paid Tier'],
    ['p', 'A. Ownership of Content: As between You and MICHIGAN, You retain all intellectual property rights in and to the research questions, prompts, uploaded documents, files, feedback, and other materials You submit to the PROGRAM (“Content”). You are solely responsible for the legality, reliability, and appropriateness of all Content You submit.'],
    ['p', 'B. Strict Confidentiality: All Content submitted by paid users, as well as the resulting generated outputs, shall be treated by MICHIGAN as strictly confidential information.'],
    ['p', 'C. AI Model Training Prohibition: Content submitted by paid users—including proprietary research prompts, search queries, and uploaded documents—will never be used by MICHIGAN, its research teams, or its third-party infrastructure providers to train, retrain, fine-tune, or improve GLKB’s underlying artificial intelligence models, machine learning algorithms, or foundational dataset indices without Your explicit written authorization.'],
    ['p', 'D. Voluntary Opt-In for Platform Improvement: Notwithstanding Subsections B and C, paid users may voluntarily elect to contribute Content or prompt data to assist MICHIGAN in ongoing research and improvement of GLKB. Data sharing for platform improvement is strictly optional and requires Your affirmative, explicit opt-in consent (e.g., via account settings or prompt selection). If You affirmatively opt-in, any Content shared will be used strictly for academic research and algorithmic optimization, governed by the University\'s research protocols. You may revoke Your opt-in consent at any time through Your account settings, which will apply prospectively to all future queries.'],
];

export default TERMS;
